<a href="https://colab.research.google.com/github/rajatsood12/ml/blob/master/demo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

class NeuralNetClassifier(nn.Module):
    def __init__(self, d, H, C):
        """
        :param d: int, input dimensionality
        :param H: list of ints, channel sizes for hidden layers
        :param C: int, number of output classes
        """
        super(NeuralNetClassifier, self).__init__()

        # Define the layers
        layers = []

        # Input layer to first hidden layer
        layers.append(nn.Linear(d, H[0]))
        layers.append(nn.Tanh())

        # Hidden layers
        for i in range(len(H) - 1):
            layers.append(nn.Linear(H[i], H[i+1]))
            layers.append(nn.Tanh())

        # Output layer (logits)
        layers.append(nn.Linear(H[-1], C))

        # Sequential model
        self.model = nn.Sequential(*layers)

    def forward(self, x):
        """
        :param x: torch.Tensor, raw input vectors of shape (batch_size, d)
        :return: torch.Tensor, logits of shape (batch_size, C)
        """
        return self.model(x)

# Testing the network
def test_network():
    # Input dimensions
    d = 10  # Dimensionality of inputs
    H = [64, 32, 16]  # Hidden layer sizes
    C = 3  # Number of output classes

    # Create a batch of input data (batch_size x d)
    batch_size = 5
    x = torch.randn(batch_size, d)

    # Initialize the model
    model = NeuralNetClassifier(d, H, C)

    # Forward pass (logits)
    logits = model(x)

    print(f"Input shape: {x.shape}")
    print(f"Logits shape: {logits.shape}")
    print(logits)

# Run the test
test_network()


Input shape: torch.Size([5, 10])
Logits shape: torch.Size([5, 3])
tensor([[ 0.1708,  0.0484, -0.0663],
        [-0.1271,  0.1017, -0.0596],
        [-0.1288,  0.0749,  0.0473],
        [-0.0864,  0.0767, -0.0107],
        [-0.1695,  0.0175,  0.0313]], grad_fn=<AddmmBackward0>)


In [2]:
import tensorflow as tf
from tensorflow.keras import layers

class NeuralNetClassifier(tf.keras.Model):
    def __init__(self, d, H, C):
        """
        :param d: int, input dimensionality
        :param H: list of ints, channel sizes for hidden layers
        :param C: int, number of output classes
        """
        super(NeuralNetClassifier, self).__init__()

        # Define the layers
        self.hidden_layers = []

        # Input layer to first hidden layer
        self.hidden_layers.append(layers.Dense(H[0], activation='tanh', input_shape=(d,)))

        # Hidden layers
        for i in range(1, len(H)):
            self.hidden_layers.append(layers.Dense(H[i], activation='tanh'))

        # Output layer (logits)
        self.output_layer = layers.Dense(C)

    def call(self, x):
        """
        :param x: tf.Tensor, raw input vectors of shape (batch_size, d)
        :return: tf.Tensor, logits of shape (batch_size, C)
        """
        for layer in self.hidden_layers:
            x = layer(x)
        return self.output_layer(x)

# Testing the network
def test_network():
    # Input dimensions
    d = 10  # Dimensionality of inputs
    H = [64, 32, 16]  # Hidden layer sizes
    C = 3  # Number of output classes

    # Create a batch of input data (batch_size x d)
    batch_size = 5
    x = tf.random.normal((batch_size, d))

    # Initialize the model
    model = NeuralNetClassifier(d, H, C)

    # Forward pass (logits)
    logits = model(x)

    print(f"Input shape: {x.shape}")
    print(f"Logits shape: {logits.shape}")
    print(logits)

# Run the test
test_network()


/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Input shape: (5, 10)
Logits shape: (5, 3)
tf.Tensor(
[[ 0.03201216  0.20704107  1.0945665 ]
 [ 0.22795568 -0.6424812   0.51847386]
 [-0.81620824 -0.5787269  -0.11312322]
 [ 0.7435062   0.11508855 -0.10669801]
 [-0.06314682 -0.0702118  -0.03763579]], shape=(5, 3), dtype=float32)
